import type { RouteManifest } from "./types";

export const adminRoutes: RouteManifest = {
  id: "administration",
  label: "Administration",
  routes: [
    {
      id: "admin-dashboard",
      path: "/admin",
      label: "Administration",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "administration",
      permissions: ["admin:dealers:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-dealers",
      path: "/admin/dealers",
      label: "Dealers",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:dealers:manage"],
      allowedRoles: ["platform-administrator"],
      apiExposed: true,
      children: [
        {
          id: "admin-dealer-detail",
          path: "/admin/dealers/[dealerId]",
          label: "Dealer Detail",
          module: "administration",
          portal: "admin",
          routeGroup: "(admin)",
          permissions: ["admin:dealers:manage"],
          allowedRoles: ["platform-administrator"],
        },
      ],
    },
    {
      id: "admin-users",
      path: "/admin/users",
      label: "Users",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:users:manage"],
      allowedRoles: ["platform-administrator"],
      apiExposed: true,
    },
    {
      id: "admin-subscriptions",
      path: "/admin/subscriptions",
      label: "Subscriptions",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:subscriptions:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-packages",
      path: "/admin/packages",
      label: "Packages",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:subscriptions:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-support",
      path: "/admin/support",
      label: "Support",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:support:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-moderation",
      path: "/admin/moderation",
      label: "Moderation",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:moderation:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-cms",
      path: "/admin/cms",
      label: "CMS",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:cms:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-creative-media-review",
      path: "/admin/creative/media-review",
      label: "Media Review",
      description:
        "Founder review and approval of candidate brand photography. Local curation tool — absent in production.",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "creative-review",
      permissions: ["admin:creative:approve"],
      allowedRoles: ["platform-administrator"],
      seoIndexable: false,
    },
    {
      id: "admin-creative-moodboard",
      path: "/admin/creative/moodboard",
      label: "Brand Moodboard",
      description:
        "The whole approved visual identity on one screen, judged as a collection rather than as candidates. Local curation tool — absent in production.",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "creative-review",
      permissions: ["admin:creative:approve"],
      allowedRoles: ["platform-administrator"],
      seoIndexable: false,
    },
    {
      id: "admin-advertising",
      path: "/admin/advertising",
      label: "Advertising",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:advertising:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-featured-listings",
      path: "/admin/featured",
      label: "Featured Listings",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:advertising:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-seo",
      path: "/admin/seo",
      label: "SEO",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "seo",
      permissions: ["admin:seo:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-analytics",
      path: "/admin/analytics",
      label: "Analytics",
      module: "analytics",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "analytics",
      permissions: ["admin:analytics:view"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-platform-health",
      path: "/admin/health",
      label: "Platform Health",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:health:view"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-ai-usage",
      path: "/admin/ai-usage",
      label: "AI Usage",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:ai-usage:view"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-system-settings",
      path: "/admin/settings",
      label: "System Settings",
      module: "settings",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "settings",
      permissions: ["admin:settings:manage"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-audit-logs",
      path: "/admin/audit",
      label: "Audit Logs",
      module: "administration",
      portal: "admin",
      routeGroup: "(admin)",
      permissions: ["admin:audit:view"],
      allowedRoles: ["platform-administrator"],
    },
    {
      id: "admin-developer-tools",
      path: "/admin/developer",
      label: "Developer Tools",
      module: "developer",
      portal: "admin",
      routeGroup: "(admin)",
      feature: "developer",
      permissions: ["admin:developer:access"],
      allowedRoles: ["platform-administrator"],
    },
  ],
};
