import type { RouteManifest } from "./types";

export const authRoutes: RouteManifest = {
  id: "authentication",
  label: "Authentication",
  routes: [
    {
      id: "auth-sign-in",
      path: "/auth/sign-in",
      label: "Sign In",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-sign-up",
      path: "/auth/sign-up",
      label: "Sign Up",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-sign-up-buyer",
      path: "/auth/sign-up/buyer",
      label: "Buyer Sign Up",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-sign-up-dealer",
      path: "/auth/sign-up/dealer",
      label: "Dealer Sign Up",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-forgot-password",
      path: "/auth/forgot-password",
      label: "Forgot Password",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-reset-password",
      path: "/auth/reset-password",
      label: "Reset Password",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-verify-email",
      path: "/auth/verify-email",
      label: "Verify Email",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
    {
      id: "auth-invite",
      path: "/auth/invite/[token]",
      label: "Team Invite",
      module: "authentication",
      portal: "auth",
      routeGroup: "(auth)",
      feature: "authentication",
      seoIndexable: false,
    },
  ],
};

export const systemRoutes: RouteManifest = {
  id: "system",
  label: "System",
  routes: [
    {
      id: "not-found",
      path: "/not-found",
      label: "Not Found",
      module: "system",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: false,
    },
    {
      id: "unauthorized",
      path: "/unauthorized",
      label: "Unauthorized",
      module: "system",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: false,
    },
    {
      id: "maintenance",
      path: "/maintenance",
      label: "Maintenance",
      module: "system",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: false,
    },
  ],
};
