import type { RouteManifest } from "./types";

export const buyerRoutes: RouteManifest = {
  id: "buyer-portal",
  label: "Buyer Portal",
  routes: [
    {
      id: "buyer-dashboard",
      path: "/buyer",
      label: "Dashboard",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:dashboard:view"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-saved-vehicles",
      path: "/buyer/saved",
      label: "Saved Vehicles",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:saved:manage"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-collections",
      path: "/buyer/collections",
      label: "Collections",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:saved:manage"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
      children: [
        {
          id: "buyer-collection-detail",
          path: "/buyer/collections/[id]",
          label: "Collection",
          module: "buyer-portal",
          portal: "buyer",
          routeGroup: "(buyer)",
          permissions: ["buyer:saved:manage"],
          allowedRoles: ["buyer"],
        },
      ],
    },
    {
      id: "buyer-saved-searches",
      path: "/buyer/searches",
      label: "Saved Searches",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "search",
      permissions: ["buyer:searches:manage"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-recently-viewed",
      path: "/buyer/recent",
      label: "Recently Viewed",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:activity:view"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-price-alerts",
      path: "/buyer/alerts",
      label: "Price Alerts",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:searches:manage"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-messages",
      path: "/buyer/messages",
      label: "Dealer Messages",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:messages:read"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
      children: [
        {
          id: "buyer-message-thread",
          path: "/buyer/messages/[threadId]",
          label: "Message Thread",
          module: "buyer-portal",
          portal: "buyer",
          routeGroup: "(buyer)",
          permissions: ["buyer:messages:read", "buyer:messages:write"],
          allowedRoles: ["buyer"],
        },
      ],
    },
    {
      id: "buyer-profile",
      path: "/buyer/profile",
      label: "Profile",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:profile:manage"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-settings",
      path: "/buyer/settings",
      label: "Settings",
      module: "settings",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "settings",
      permissions: ["buyer:profile:manage"],
      allowedRoles: ["buyer"],
    },
    {
      id: "buyer-notifications",
      path: "/buyer/notifications",
      label: "Notifications",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "notifications",
      permissions: ["buyer:profile:manage"],
      allowedRoles: ["buyer"],
      mobileSupported: true,
    },
    {
      id: "buyer-activity",
      path: "/buyer/activity",
      label: "Activity",
      module: "buyer-portal",
      portal: "buyer",
      routeGroup: "(buyer)",
      feature: "buyer-portal",
      permissions: ["buyer:activity:view"],
      allowedRoles: ["buyer"],
    },
  ],
};
