import type { RouteManifest } from "./types";

export const dealerRoutes: RouteManifest = {
  id: "dealer-command-centre",
  label: "Dealer Command Centre",
  routes: [
    {
      id: "dealer-dashboard",
      path: "/dealer",
      label: "Executive Dashboard",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "dealer-command-centre",
      permissions: ["dealer:dashboard:view"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      mobileSupported: true,
    },
    {
      id: "dealer-inventory",
      path: "/dealer/inventory",
      label: "Inventory",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "inventory",
      permissions: ["dealer:inventory:read"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      apiExposed: true,
      mobileSupported: true,
    },
    {
      id: "dealer-market-intelligence",
      path: "/dealer/market",
      label: "Market Intelligence",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "intelligence",
      permissions: ["dealer:inventory:read"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      apiExposed: true,
      mobileSupported: true,
    },
    {
      id: "dealer-vehicle-manager",
      path: "/dealer/inventory/[vehicleId]",
      label: "Vehicle Manager",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "vehicle",
      permissions: ["dealer:vehicle:manage"],
      allowedRoles: ["salesperson", "branch-manager", "dealer-owner"],
      apiExposed: true,
    },
    {
      id: "dealer-media-library",
      path: "/dealer/media",
      label: "Media Library",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "media",
      permissions: ["dealer:media:manage"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      apiExposed: true,
    },
    {
      id: "dealer-marketing-studio",
      path: "/dealer/marketing",
      label: "Marketing Studio",
      module: "marketing-studio",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "marketing-studio",
      permissions: ["dealer:marketing:read"],
      allowedRoles: ["salesperson", "branch-manager", "dealer-owner"],
      children: [
        {
          id: "marketing-campaigns",
          path: "/dealer/marketing/campaigns",
          label: "Campaigns",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          feature: "marketing-studio",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-social",
          path: "/dealer/marketing/social",
          label: "Social Posts",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-vehicle-campaigns",
          path: "/dealer/marketing/vehicle-campaigns",
          label: "Vehicle Campaigns",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-media-generator",
          path: "/dealer/marketing/media-generator",
          label: "Media Generator",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-video-studio",
          path: "/dealer/marketing/video",
          label: "Video Studio",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-poster-generator",
          path: "/dealer/marketing/posters",
          label: "Poster Generator",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-qr-generator",
          path: "/dealer/marketing/qr",
          label: "QR Generator",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-brand-templates",
          path: "/dealer/marketing/templates",
          label: "Brand Templates",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:brand:manage"],
        },
        {
          id: "marketing-content-calendar",
          path: "/dealer/marketing/calendar",
          label: "Content Calendar",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:write"],
        },
        {
          id: "marketing-library",
          path: "/dealer/marketing/library",
          label: "Marketing Library",
          module: "marketing-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:marketing:read"],
        },
      ],
    },
    {
      id: "dealer-ai-studio",
      path: "/dealer/ai",
      label: "AI Studio",
      module: "ai-studio",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "ai-studio",
      permissions: ["dealer:ai:read"],
      allowedRoles: ["branch-manager", "dealer-owner"],
      children: [
        {
          id: "ai-listings",
          path: "/dealer/ai/listings",
          label: "AI Listings",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:write"],
        },
        {
          id: "ai-insights",
          path: "/dealer/ai/insights",
          label: "AI Insights",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:read"],
        },
        {
          id: "ai-recommendations",
          path: "/dealer/ai/recommendations",
          label: "AI Recommendations",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:read"],
        },
        {
          id: "ai-image-analysis",
          path: "/dealer/ai/image-analysis",
          label: "AI Image Analysis",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:write"],
        },
        {
          id: "ai-seo",
          path: "/dealer/ai/seo",
          label: "AI SEO",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:write"],
        },
        {
          id: "ai-copywriting",
          path: "/dealer/ai/copywriting",
          label: "AI Copywriting",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:write"],
        },
        {
          id: "ai-market-trends",
          path: "/dealer/ai/market-trends",
          label: "AI Market Trends",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:read"],
        },
        {
          id: "ai-dealer-assistant",
          path: "/dealer/ai/assistant",
          label: "AI Dealer Assistant",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:write"],
        },
        {
          id: "ai-future-modules",
          path: "/dealer/ai/modules",
          label: "Future AI Modules",
          module: "ai-studio",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:ai:read"],
        },
      ],
    },
    {
      id: "dealer-lead-centre",
      path: "/dealer/leads",
      label: "Lead Centre",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "crm",
      permissions: ["dealer:leads:read"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      mobileSupported: true,
    },
    {
      id: "dealer-crm",
      path: "/dealer/crm",
      label: "CRM",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "crm",
      permissions: ["dealer:crm:read"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      apiExposed: true,
    },
    {
      id: "dealer-analytics",
      path: "/dealer/analytics",
      label: "Analytics",
      module: "analytics",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "analytics",
      permissions: ["dealer:analytics:view"],
      allowedRoles: ["salesperson", "branch-manager", "dealer-owner"],
      children: [
        {
          id: "analytics-performance",
          path: "/dealer/analytics/performance",
          label: "Performance",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-inventory",
          path: "/dealer/analytics/inventory",
          label: "Inventory Analytics",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-marketing",
          path: "/dealer/analytics/marketing",
          label: "Marketing Analytics",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-traffic",
          path: "/dealer/analytics/traffic",
          label: "Traffic",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-search",
          path: "/dealer/analytics/search",
          label: "Search Analytics",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-leads",
          path: "/dealer/analytics/leads",
          label: "Lead Analytics",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-engagement",
          path: "/dealer/analytics/engagement",
          label: "Engagement",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-stock-age",
          path: "/dealer/analytics/stock-age",
          label: "Stock Age",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-pricing-trends",
          path: "/dealer/analytics/pricing",
          label: "Pricing Trends",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-dealer-growth",
          path: "/dealer/analytics/growth",
          label: "Dealer Growth",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:analytics:view"],
        },
        {
          id: "analytics-branch-comparison",
          path: "/dealer/analytics/branches",
          label: "Branch Comparison",
          module: "analytics",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:branches:view"],
        },
      ],
    },
    {
      id: "dealer-reports",
      path: "/dealer/reports",
      label: "Reports",
      module: "analytics",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "analytics",
      permissions: ["dealer:reports:view"],
      allowedRoles: ["branch-manager", "dealer-owner"],
    },
    {
      id: "dealer-seo-centre",
      path: "/dealer/seo",
      label: "SEO Centre",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "seo",
      permissions: ["dealer:seo:manage"],
      allowedRoles: ["branch-manager", "dealer-owner"],
    },
    {
      id: "dealer-website-manager",
      path: "/dealer/website",
      label: "Website Manager",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:website:manage"],
      allowedRoles: ["dealer-owner"],
    },
    {
      id: "dealer-team",
      path: "/dealer/team",
      label: "Team Management",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:team:view"],
      allowedRoles: ["branch-manager", "dealer-owner"],
    },
    {
      id: "dealer-branches",
      path: "/dealer/branches",
      label: "Branches",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:branches:view"],
      allowedRoles: ["branch-manager", "dealer-owner"],
      children: [
        {
          id: "dealer-branch-detail",
          path: "/dealer/branches/[branchId]",
          label: "Branch",
          module: "dealer-command-centre",
          portal: "dealer",
          routeGroup: "(dealer)",
          permissions: ["dealer:branches:manage"],
          allowedRoles: ["dealer-owner"],
        },
      ],
    },
    {
      id: "dealer-profile",
      path: "/dealer/profile",
      label: "Dealer Profile",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "dealership",
      permissions: ["dealer:profile:manage"],
      allowedRoles: ["branch-manager", "dealer-owner"],
    },
    {
      id: "dealer-brand-assets",
      path: "/dealer/brand",
      label: "Brand Assets",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:brand:manage"],
      allowedRoles: ["dealer-owner"],
    },
    {
      id: "dealer-documents",
      path: "/dealer/documents",
      label: "Documents",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:documents:manage"],
      allowedRoles: ["dealer-owner"],
    },
    {
      id: "dealer-billing",
      path: "/dealer/billing",
      label: "Billing",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:billing:view"],
      allowedRoles: ["dealer-owner"],
    },
    {
      id: "dealer-settings",
      path: "/dealer/settings",
      label: "Settings",
      module: "settings",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "settings",
      permissions: ["dealer:settings:view"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
    },
    {
      id: "dealer-notifications",
      path: "/dealer/notifications",
      label: "Notifications",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      feature: "notifications",
      permissions: ["dealer:notifications:manage"],
      allowedRoles: ["dealer", "salesperson", "branch-manager", "dealer-owner"],
      mobileSupported: true,
    },
    {
      id: "dealer-audit-logs",
      path: "/dealer/audit",
      label: "Audit Logs",
      module: "dealer-command-centre",
      portal: "dealer",
      routeGroup: "(dealer)",
      permissions: ["dealer:audit:view"],
      allowedRoles: ["branch-manager", "dealer-owner"],
    },
  ],
};
