import type { RouteManifest } from "./types";

export const developerRoutes: RouteManifest = {
  id: "developer",
  label: "Developer",
  routes: [
    {
      id: "developer-dashboard",
      path: "/developer",
      label: "Developer",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      feature: "developer",
      permissions: ["developer:docs:view"],
      allowedRoles: ["developer", "platform-administrator"],
    },
    {
      id: "developer-api-keys",
      path: "/developer/api-keys",
      label: "API Keys",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:api-keys:manage"],
      allowedRoles: ["developer"],
      apiExposed: true,
    },
    {
      id: "developer-webhooks",
      path: "/developer/webhooks",
      label: "Webhooks",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:webhooks:manage"],
      allowedRoles: ["developer"],
      apiExposed: true,
    },
    {
      id: "developer-logs",
      path: "/developer/logs",
      label: "Logs",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:logs:view"],
      allowedRoles: ["developer"],
    },
    {
      id: "developer-feature-flags",
      path: "/developer/flags",
      label: "Feature Flags",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:flags:manage"],
      allowedRoles: ["developer"],
    },
    {
      id: "developer-background-jobs",
      path: "/developer/jobs",
      label: "Background Jobs",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:jobs:view"],
      allowedRoles: ["developer"],
    },
    {
      id: "developer-queue-monitor",
      path: "/developer/queue",
      label: "Queue Monitor",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:queue:monitor"],
      allowedRoles: ["developer"],
    },
    {
      id: "developer-documentation",
      path: "/developer/docs",
      label: "Documentation",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:docs:view"],
      allowedRoles: ["developer"],
    },
    {
      id: "developer-environment",
      path: "/developer/environment",
      label: "Environment",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:env:view"],
      allowedRoles: ["developer"],
    },
    {
      id: "developer-monitoring",
      path: "/developer/monitoring",
      label: "Monitoring",
      module: "developer",
      portal: "developer",
      routeGroup: "(developer)",
      permissions: ["developer:monitoring:view"],
      allowedRoles: ["developer"],
    },
  ],
};

export const apiRoutes: RouteManifest = {
  id: "api",
  label: "API",
  routes: [
    {
      id: "api-v1",
      path: "/api/v1",
      label: "API v1",
      module: "developer",
      portal: "developer",
      routeGroup: "(api)",
      description: "Versioned REST API for mobile and partner integrations",
      apiExposed: true,
      mobileSupported: true,
      children: [
        {
          id: "api-vehicles",
          path: "/api/v1/vehicles",
          label: "Vehicles API",
          module: "marketplace",
          portal: "developer",
          routeGroup: "(api)",
          feature: "vehicle",
          apiExposed: true,
          mobileSupported: true,
        },
        {
          id: "api-dealers",
          path: "/api/v1/dealers",
          label: "Dealers API",
          module: "marketplace",
          portal: "developer",
          routeGroup: "(api)",
          feature: "dealership",
          apiExposed: true,
          mobileSupported: true,
        },
        {
          id: "api-search",
          path: "/api/v1/search",
          label: "Search API",
          module: "marketplace",
          portal: "developer",
          routeGroup: "(api)",
          feature: "search",
          apiExposed: true,
          mobileSupported: true,
        },
        {
          id: "api-inventory",
          path: "/api/v1/inventory",
          label: "Inventory API",
          module: "dealer-command-centre",
          portal: "developer",
          routeGroup: "(api)",
          feature: "inventory",
          apiExposed: true,
        },
        {
          id: "api-partners",
          path: "/api/v1/partners",
          label: "Partner API",
          module: "developer",
          portal: "developer",
          routeGroup: "(api)",
          description: "Future partner integration endpoints",
          apiExposed: true,
        },
      ],
    },
  ],
};
