import type { RouteManifest } from "./types";

export const operationsRoutes: RouteManifest = {
  id: "operations-centre",
  label: "Operations Centre",
  routes: [
    {
      id: "operations-dashboard",
      path: "/operations/dashboard",
      label: "Dashboard",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: [
        "platform-owner",
        "operations-director",
        "dealer-success",
        "marketplace",
        "revenue",
        "finance",
        "support",
        "marketing",
        "moderation",
      ],
    },
    {
      id: "operations-onboarding-centre",
      path: "/operations/onboarding-centre",
      label: "Onboarding Centre",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-verification",
      path: "/operations/verification",
      label: "Verification",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-quality-centre",
      path: "/operations/quality-centre",
      label: "Quality Centre",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management",
      path: "/operations/dealer-management",
      label: "Dealer Management",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-applications",
      path: "/operations/dealer-management/applications",
      label: "Dealer Management Applications",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-dealerships",
      path: "/operations/dealer-management/dealerships",
      label: "Dealer Management Dealerships",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-branches",
      path: "/operations/dealer-management/branches",
      label: "Dealer Management Branches",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-dealer-users",
      path: "/operations/dealer-management/dealer-users",
      label: "Dealer Management Dealer Users",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-subscriptions",
      path: "/operations/dealer-management/subscriptions",
      label: "Dealer Management Subscriptions",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-billing",
      path: "/operations/dealer-management/billing",
      label: "Dealer Management Billing",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-performance",
      path: "/operations/dealer-management/performance",
      label: "Dealer Management Performance",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-health",
      path: "/operations/dealer-management/health",
      label: "Dealer Management Health",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-notes",
      path: "/operations/dealer-management/notes",
      label: "Dealer Management Notes",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-timeline",
      path: "/operations/dealer-management/timeline",
      label: "Dealer Management Timeline",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-documents",
      path: "/operations/dealer-management/documents",
      label: "Dealer Management Documents",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-contracts",
      path: "/operations/dealer-management/contracts",
      label: "Dealer Management Contracts",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-management-audit",
      path: "/operations/dealer-management/audit",
      label: "Dealer Management Audit",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success"],
    },
    {
      id: "operations-dealer-intelligence",
      path: "/operations/dealer-intelligence",
      label: "Dealer Intelligence",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-discovery-queue",
      path: "/operations/dealer-intelligence/discovery-queue",
      label: "Dealer Intelligence Discovery Queue",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-dealership-directory",
      path: "/operations/dealer-intelligence/dealership-directory",
      label: "Dealer Intelligence Dealership Directory",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-dealer-profiles",
      path: "/operations/dealer-intelligence/dealer-profiles",
      label: "Dealer Intelligence Dealer Profiles",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-branch-discovery",
      path: "/operations/dealer-intelligence/branch-discovery",
      label: "Dealer Intelligence Branch Discovery",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-brand-detection",
      path: "/operations/dealer-intelligence/brand-detection",
      label: "Dealer Intelligence Brand Detection",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-contact-discovery",
      path: "/operations/dealer-intelligence/contact-discovery",
      label: "Dealer Intelligence Contact Discovery",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-website-analysis",
      path: "/operations/dealer-intelligence/website-analysis",
      label: "Dealer Intelligence Website Analysis",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-ai-classification",
      path: "/operations/dealer-intelligence/ai-classification",
      label: "Dealer Intelligence AI Classification",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-verification",
      path: "/operations/dealer-intelligence/verification",
      label: "Dealer Intelligence Verification",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-duplicate-detection",
      path: "/operations/dealer-intelligence/duplicate-detection",
      label: "Dealer Intelligence Duplicate Detection",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-change-monitoring",
      path: "/operations/dealer-intelligence/change-monitoring",
      label: "Dealer Intelligence Change Monitoring",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-data-quality",
      path: "/operations/dealer-intelligence/data-quality",
      label: "Dealer Intelligence Data Quality",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-dealer-intelligence-activity",
      path: "/operations/dealer-intelligence/activity",
      label: "Dealer Intelligence Activity",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "marketplace"],
    },
    {
      id: "operations-applications-centre",
      path: "/operations/applications-centre",
      label: "Applications Centre",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "dealer-success", "finance", "support"],
    },
    {
      id: "operations-marketplace-control",
      path: "/operations/marketplace-control",
      label: "Marketplace Control",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "marketplace", "moderation"],
    },
    {
      id: "operations-revenue-centre",
      path: "/operations/revenue-centre",
      label: "Revenue Centre",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "revenue", "finance"],
    },
    {
      id: "operations-advertising-centre",
      path: "/operations/advertising-centre",
      label: "Advertising Centre",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "marketing", "marketplace"],
    },
    {
      id: "operations-partner-centre",
      path: "/operations/partner-centre",
      label: "Partner Centre",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "revenue", "finance", "marketing"],
    },
    {
      id: "operations-business-intelligence",
      path: "/operations/business-intelligence",
      label: "Business Intelligence",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "revenue", "finance", "marketplace"],
    },
    {
      id: "operations-settings",
      path: "/operations/settings",
      label: "Settings",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:manage"],
      allowedRoles: ["platform-owner", "operations-director"],
    },
    {
      id: "operations-audit-logs",
      path: "/operations/audit-logs",
      label: "Audit Logs",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:view"],
      allowedRoles: ["platform-owner", "operations-director", "moderation", "support"],
    },
    {
      id: "operations-workers",
      path: "/operations/workers",
      label: "Workers",
      module: "operations",
      portal: "operations",
      routeGroup: "(operations)",
      permissions: ["operations:manage"],
      allowedRoles: ["platform-owner", "operations-director"],
    },
  ],
};
