import type { RouteManifest } from "./types";

export const publicRoutes: RouteManifest = {
  id: "public",
  label: "Public",
  routes: [
    {
      id: "home",
      path: "/",
      label: "Home",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
      mobileSupported: true,
    },
    {
      id: "vehicle-search",
      path: "/search",
      label: "Vehicle Search",
      module: "marketplace",
      portal: "public",
      routeGroup: "(marketplace)",
      feature: "search",
      seoIndexable: true,
      mobileSupported: true,
    },
    {
      id: "vehicle-details",
      path: "/vehicle/[slug]",
      label: "Vehicle Details",
      module: "marketplace",
      portal: "public",
      routeGroup: "(marketplace)",
      feature: "vehicle",
      seoIndexable: true,
      apiExposed: true,
      mobileSupported: true,
    },
    {
      id: "dealer-profiles",
      path: "/dealers/[slug]",
      label: "Dealer Profiles",
      module: "marketplace",
      portal: "public",
      routeGroup: "(marketplace)",
      feature: "dealership",
      seoIndexable: true,
      apiExposed: true,
      mobileSupported: true,
    },
    {
      id: "featured-dealers",
      path: "/dealers/featured",
      label: "Featured Dealers",
      module: "marketplace",
      portal: "public",
      routeGroup: "(marketplace)",
      feature: "dealership",
      seoIndexable: true,
    },
    {
      id: "new-arrivals",
      path: "/vehicles/new-arrivals",
      label: "New Arrivals",
      module: "marketplace",
      portal: "public",
      routeGroup: "(marketplace)",
      feature: "marketplace",
      seoIndexable: true,
    },
    {
      id: "lifestyle-collections",
      path: "/collections/[slug]",
      label: "Lifestyle Collections",
      module: "marketplace",
      portal: "public",
      routeGroup: "(marketplace)",
      feature: "marketplace",
      seoIndexable: true,
    },
    {
      id: "buying-guides",
      path: "/guides",
      label: "Buying Guides",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      feature: "seo",
      seoIndexable: true,
      children: [
        {
          id: "buying-guide-detail",
          path: "/guides/[slug]",
          label: "Buying Guide",
          module: "public",
          portal: "public",
          routeGroup: "(public)",
          seoIndexable: true,
        },
      ],
    },
    {
      id: "vehicle-reviews",
      path: "/reviews",
      label: "Vehicle Reviews",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
      children: [
        {
          id: "vehicle-review-detail",
          path: "/reviews/[slug]",
          label: "Vehicle Review",
          module: "public",
          portal: "public",
          routeGroup: "(public)",
          seoIndexable: true,
        },
      ],
    },
    {
      id: "news",
      path: "/news",
      label: "News",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
      children: [
        {
          id: "news-article",
          path: "/news/[slug]",
          label: "News Article",
          module: "public",
          portal: "public",
          routeGroup: "(public)",
          seoIndexable: true,
        },
      ],
    },
    {
      id: "about",
      path: "/about",
      label: "About",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
    },
    {
      id: "contact",
      path: "/contact",
      label: "Contact",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
    },
    {
      id: "support",
      path: "/support",
      label: "Support",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
    },
    {
      id: "faq",
      path: "/faq",
      label: "FAQ",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
    },
    {
      id: "privacy",
      path: "/privacy",
      label: "Privacy",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
    },
    {
      id: "terms",
      path: "/terms",
      label: "Terms",
      module: "public",
      portal: "public",
      routeGroup: "(public)",
      seoIndexable: true,
    },
  ],
};
