/**
 * GENERATED by scripts/media/approve-selection.mjs — do not edit by hand.
 *
 * Every entry here is a Founder-approved brand asset. Re-run the approval script to change one.
 */

export const PREMIUM_MEDIA_MANIFEST = {} as const;

export type PremiumMediaId = keyof typeof PREMIUM_MEDIA_MANIFEST;
