/**
 * SURF FOR CARS — Application Map
 *
 * Complete module inventory — the master blueprint of the platform.
 */

export const APPLICATION_MAP = {
  public: {
    id: "public",
    label: "Public",
    description: "Marketing, discovery, and unauthenticated surfaces",
    modules: [
      "Home",
      "Vehicle Search",
      "Vehicle Details",
      "Dealer Profiles",
      "Featured Dealers",
      "New Arrivals",
      "Lifestyle Collections",
      "Buying Guides",
      "Vehicle Reviews",
      "News",
      "About",
      "Contact",
      "Support",
      "FAQ",
      "Privacy",
      "Terms",
    ],
  },
  buyerPortal: {
    id: "buyer-portal",
    label: "Buyer Portal",
    description: "Registered buyer account and activity",
    modules: [
      "Dashboard",
      "Saved Vehicles",
      "Collections",
      "Saved Searches",
      "Recently Viewed",
      "Price Alerts",
      "Dealer Messages",
      "Profile",
      "Settings",
      "Notifications",
      "Activity",
    ],
  },
  dealerCommandCentre: {
    id: "dealer-command-centre",
    label: "Dealer Command Centre",
    description: "Dealer operations and growth hub",
    modules: [
      "Executive Dashboard",
      "Inventory",
      "Vehicle Manager",
      "Media Library",
      "Marketing Studio",
      "AI Studio",
      "Lead Centre",
      "CRM",
      "Analytics",
      "Reports",
      "SEO Centre",
      "Website Manager",
      "Team Management",
      "Branches",
      "Dealer Profile",
      "Brand Assets",
      "Documents",
      "Billing",
      "Settings",
      "Notifications",
      "Audit Logs",
    ],
  },
  marketingStudio: {
    id: "marketing-studio",
    label: "Marketing Studio",
    description: "Campaign creation and content production",
    parent: "dealer-command-centre",
    modules: [
      "Campaigns",
      "Social Posts",
      "Vehicle Campaigns",
      "Media Generator",
      "Video Studio",
      "Poster Generator",
      "QR Generator",
      "Brand Templates",
      "Content Calendar",
      "Marketing Library",
    ],
  },
  aiStudio: {
    id: "ai-studio",
    label: "AI Studio",
    description: "AI-powered dealer growth tools",
    parent: "dealer-command-centre",
    modules: [
      "AI Listings",
      "AI Insights",
      "AI Recommendations",
      "AI Image Analysis",
      "AI SEO",
      "AI Copywriting",
      "AI Market Trends",
      "AI Dealer Assistant",
      "Future AI Modules",
    ],
  },
  analytics: {
    id: "analytics",
    label: "Analytics",
    description: "Performance intelligence across dealer and platform",
    modules: [
      "Performance",
      "Inventory Analytics",
      "Marketing Analytics",
      "Traffic",
      "Search Analytics",
      "Lead Analytics",
      "Engagement",
      "Stock Age",
      "Pricing Trends",
      "Dealer Growth",
      "Branch Comparison",
    ],
  },
  administration: {
    id: "administration",
    label: "Administration",
    description: "Platform operations and governance",
    modules: [
      "Dealers",
      "Users",
      "Subscriptions",
      "Packages",
      "Support",
      "Moderation",
      "CMS",
      "Advertising",
      "Featured Listings",
      "SEO",
      "Analytics",
      "Platform Health",
      "AI Usage",
      "System Settings",
      "Audit Logs",
      "Developer Tools",
    ],
  },
  developer: {
    id: "developer",
    label: "Developer",
    description: "API, integrations, and platform extensibility",
    modules: [
      "API Keys",
      "Webhooks",
      "Logs",
      "Feature Flags",
      "Background Jobs",
      "Queue Monitor",
      "Documentation",
      "Environment",
      "Monitoring",
    ],
  },
} as const;

export type ApplicationSectionId = keyof typeof APPLICATION_MAP;
