-- PCP-013A P4 (follow-up) — the last fabricated contact details.
--
-- The preceding migration cleared 128 dealerships by seed signature. Three values survived it, because they
-- were generated by a different producer: the SFC-008 onboarding test harness rather than the demo seed.
--
--   owner@capemotors.co.za   / hq@capemotors.co.za   — plausible, but no such mailbox exists
--   +2721475665              / +2721689217           — eight digits after the dialling code, so they did
--                                                      not match the nine-digit SA pattern used before
--
-- This is the point the previous migration's comment was making in the abstract, now demonstrated: a
-- fabrication that looks *almost* right survives the filter written for the fabrications that looked wrong.
-- Pattern-matching finds the artefacts you already know about. It is not a substitute for the platform
-- recording where a value came from, which is what the provenance model exists to do.
--
-- Scoped to the two known test dealerships by id, so nothing else can be caught. `capemotors.co.za` does
-- not resolve, so unlike the demo domains there was no third-party exposure here.
--
-- Note for the Founder Quality Centre (P6): `dealership-36ab80f2-…` carries 22 vehicles — the deepest
-- single inventory on the platform — and its `business_name` is "Cape Motors Final 1782824475665". The
-- public profile is unaffected (it displays `trading_name`, "Cape Motors", and the timestamped legal name
-- is already suppressed by the placeholder filter), but a test fixture should not be the largest dealer in
-- a production marketplace. Flagged rather than renamed: inventing a legal name is the same mistake in the
-- opposite direction.

begin;

update public.dealerships
set email     = null,
    telephone = null
where id in (
  'dealership-36ab80f2-3057-4831-af89-18ed1403a1bb',
  'dealership-owner-owner-sfc008-1782818327813-capemotors-co-za'
);

update public.dealership_branches
set email     = null,
    telephone = null
where dealership_id in (
  'dealership-36ab80f2-3057-4831-af89-18ed1403a1bb',
  'dealership-owner-owner-sfc008-1782818327813-capemotors-co-za'
);

commit;
